#################
# GLOBAL PARAMS #
#################
base_dir: '/data/prabhupad/scratch/data/csr/experiments_2/'
seed: &seed 42


###############
# Data params #
###############
dataset_params:
  raw_dataset_file: "/home/ppradhan/Documents/my_learnings/my_uni_stuffs/sa_data_storage/training.1600000.processed.noemoticon.csv"
  max_length: 128
  batch_size: 32




###################
# Training params #
###################
training_params:
  base-model-name: "cardiffnlp/twitter-roberta-base"
  train_mode: "fine_tune_base_model"
  tokenizer: 'bert-base-uncased'
  learning_rate: 1e-5
  num_epochs: 5
