FROM python:3.10.5-buster

RUN mkdir container_src

COPY sa_app/dashboard/app.py container_src/

COPY sa_app/dashboard/requirements.txt container_src/

COPY sa_app/dashboard/sample.csv container_src/

RUN pip install -r container_src/requirements.txt


EXPOSE 8501

CMD ["streamlit", "run", "container_src/app.py"]
