apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
      - name: inference-container
        image: prabhupad26/sa_analytics_inference:0.1
        ports:
        - containerPort: 5000  # Port for Flask app
          name: http-port
        env:
        - name: WANDB_API_KEY
          value: WANDB_API_KEY_VALUE
---
apiVersion: v1
kind: Service
metadata:
  name: inference
spec:
  selector:
    app: inference
  ports:
    - protocol: TCP
      port: 5000  # Port for Flask app
      targetPort: 5000
