name: Run Docker on GCE

on:
  push:
    branches:
      - 'training/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Run Docker Container
        run: |
          gcloud compute ssh ${{ vars.TRAINING_VM_NAME}} --zone ${{ vars.TRAINING_ZONE }} --command "docker run -e WANDB_API_KEY=${{ secrets.WANDB_API_KEY_VALUE }} prabhupad26/sa_analytics_training"
