name: Build and Publish Training Docker Image
on:
  pull_request:
    paths:
      - sa_app/src/pyproject.toml
      - sa_app/config_files/app_cfg.yml
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Tag Docker image
      run: |
        docker build -t sa_analytics_training -f Dockerfile_training .
        docker tag sa_analytics_training prabhupad26/sa_analytics_training:0.3

    - name: Push Docker image to Docker Hub
      run: docker push prabhupad26/sa_analytics_training:0.3
