name: Build and Publish Inference Docker Image
on:
  pull_request:
    paths:
      - sa_app/src/pyproject.toml
      - sa_app/config_files/app_cfg.yml
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Tag Docker image
      run: |
        docker build -t sa_analytics_inference -f Dockerfile_Inference .
        docker tag sa_analytics_inference prabhupad26/sa_analytics_inference:0.6

    - name: Push Docker image to Docker Hub
      run: docker push prabhupad26/sa_analytics_inference:0.6
