name: CI - Python Package using Conda

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd sa_app/src
        python -m spacy download en_core_web_sm
        curl -sSL https://install.python-poetry.org | python3 -
        poetry build
    - name: Test with pytest
      run: |
        conda install pytest
        cd sa_app/src
        pip install -e .
        pytest tests/
