name: Python Package using Conda

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd sa_app/src
        pip install -r requirements.txt
        python -m spacy download en_code_web_sm
    - name: Test with pytest
      run: |
        conda install pytest
        cd sa_app/src
        pytest tests/
